url: https://devscariocas.github.io
baseurl: /

# Site settings
title: DevsCariocas
email: devscarioca@gmail.com
description: "Somos desenvolvedores apaixonados por codificar e trocar experiências"


# Team names, titles and social links
people:
- name: Daniel Rocha
  pic: 1
  position: Desenvolvedor
  social:
    - title: github
      url: https://github.com/rochadaniel

- name: Jonathan Bijos
  pic: 2
  position: Desenvolvedor
  social:
    - title: github
      url: http://github.com/jekyll

- name: Arthur Marba
  pic: 3
  position: Criação
  # social:
  #   - title: github
  #     url: http://github.com/jekyll

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/rochadaniel/devscariocas

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
